# Generated by Django 2.2.7 on 2019-11-11 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Chat message', 'verbose_name_plural': 'Chat message'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Chat room', 'verbose_name_plural': 'Chats rooms'},
        ),
    ]
