# Generated by Django 2.2.7 on 2019-11-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0002_auto_20191111_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Chat room', 'verbose_name_plural': 'Chat rooms'},
        ),
    ]
